# Generated by Django 5.1 on 2024-08-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='capture',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='capture',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
