# Generated by Django 5.1 on 2024-08-19 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0002_capture_user_alter_capture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
