# Generated by Django 5.1 on 2024-08-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0003_alter_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishing_app.species'),
        ),
    ]
