# Generated by Django 5.1 on 2024-08-19 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0004_alter_capture_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='capture',
            name='species',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
