# Generated by Django 5.1 on 2024-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0005_alter_capture_date_alter_capture_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='description',
        ),
        migrations.AddField(
            model_name='species',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='habitat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='id_worms',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
