# Generated by Django 5.1 on 2024-08-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0006_remove_species_description_species_authority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
    ]
