# Generated by Django 5.1 on 2024-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0008_alter_capture_species_alter_capture_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='id_worms',
            new_name='id_fishbase',
        ),
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
